### ISSUE TITLE
Dumps coming in with no files

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-downloads-website#107]
Sunday August 26 is an example.

![screenshot - 08292016 - 07 33 44 pm](https://cloud.githubusercontent.com/assets/9993/18074174/b2a4716c-6e1f-11e6-83e8-0d70fc7095a1.png)

My view is that we should not be publishing empty pages like this and our `complete()` manager method should be excluding them. It is not.

**Comment by gordonje** [comment]
I believe the [manager method](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/managers.py#L53-L57) in the raw-data app is working correctly (just exclude `RawDataVersion` instances where the `update_finish_datatime` is `NULL`.

I think the problem is that the dev ec2 instance was running an older release candidate of the raw-data app, one that was properly handling the cases when the download zip was out of sync with the download metadata. And the crontab on that server was still set to download to earlier.

Fixed that, and I'm in the process of copying the prod db and data archive s3 bucket to their dev counterparts.
