### ISSUE TITLE
Should we be republishing our data on Kaggle?

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-downloads-website#168]
Twitter user [@dam_io suggests](https://twitter.com/dam_io/status/781792560746487808): "you could publish your dataset on kaggle to save a bit of hassle."

I'm not familiar with their service, but I'm open to third-party republishing. Can someone explain to me here what that would take?

**Comment by mdamien** [comment]
(@dam_io here) I'm no kaggle expert but you can check the other datasets at https://www.kaggle.com/datasets and see if it fits. Then it's just a matter of creating an account because anybody can publish their own.

<img src='https://cloud.githubusercontent.com/assets/1469823/18999407/b4df38d6-873d-11e6-8167-db418dbdeff8.png' height=150 />

The hard part may be to synchronize both datasets.

**Comment by palewire** [comment]
Synchronization is a requirement for our dataset, which changes daily. Do you know any Kaggle datasets that do that now?

**Comment by mdamien** [comment]
There's the [meta-kaggle](https://www.kaggle.com/kaggle/meta-kaggle) dataset for example, you can see the versionning at the bottom.

You don't need to synchronize daily with kaggle, monthly should be sufficient.

**Comment by palewire** [comment]
Thanks. Do you know if there's a way to automate the update via an API or other method?
