### ISSUE TITLE
Redesign the Latest Download page to feature our new processed files

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-downloads-website#176]
As we prepare to release our first round of processed files, we need to figure out how we're going to feature them on our site. 

Currently, [our downloads page](https://calaccess.californiacivicdata.org/downloads/latest/) features individual downloads of the "raw" files from CAL-ACCESS, as well as a ZIP at the top containing all raw tables.

![screenshot from 2017-08-17 17-34-59](https://user-images.githubusercontent.com/9993/29439454-87efda92-8372-11e7-8cfb-c2336d9d8044.png)

This page needs to grow to include and prioritize a new set of processed files. The first batch will include:

- [x] 25 relational files that repackage all of the elections, candidates and ballot measures as clean CSVs in our new OpenCivicData schema
- [x] 2 flat files that join those relational tables into easy to grab and analyze spreadsheets

The 25 relational tables are listed below. We have not finalized the flat files yet but they are likely to include at least one with all our data on candidates and another with all our data on ballot measures.

![screenshot from 2017-08-17 17-37-57](https://user-images.githubusercontent.com/9993/29439515-f279f1fe-8372-11e7-84da-667e147931ea.png)

It's my view that these files should be somehow separated and prioritized over the raw files. Perhaps we have an identical separate list above the existing raw list. Perhaps we somehow reduce the prominence of the raw files in the hierarchy so they don't take up as much space. But we need to figure something out.

Other things I see on the page that I think need to change:

- [x] The chatter under the headline needs to be update to expand the definition of what we're providing beyond CAL-ACCESS. 
- [x] The full archive subhed and chatter needs to change to reflect we have more data to offer
- [x] We need to finalize the language for how we are going to refer to these new files (as discussed in #175)

@aboutaaron I am tagging you here. Sound off when ready.

**Comment by hcharley** [comment]
An idea:

![ccdc-downloads-page](https://user-images.githubusercontent.com/1542740/29443641-3205e7ae-838e-11e7-90e8-b7fe6868d4b7.png)

The links to the individual spreadsheets could take you to the same type of list view that is currently on the latest download page.

The Picasso bulls were inspired by the CCDC's bear logo and illustrate the degrees of simplicity in usage between the 3 types of archives. I'm not overly attached to it, I just thought it might be cute.

I didn't include links to previous downloads, but that should be easy enough to place as a section at the bottom of the page or as a link in the header/nav as it is right now.

Another thing that probably should use some thought is linking off to the documentation for the contents of each archive. I was thinking that having a visible link, maybe inline in the descriptions would be good, but also maybe the download buttons get replaced by a button that has copy like this: "Download started, read the docs while you wait->"

**Comment by aboutaaron** [comment]
![desktop](https://user-images.githubusercontent.com/856628/30357154-3b2b9e46-980b-11e7-8791-7737ea24eb62.png)

Here's a first swing at the top. We can work through language and figure out how to best display the data. We can chat more on the call. I'll flesh out the mocks by Sunday, but feel free to drop more ideas here.

**Comment by palewire** [comment]
Excellent. Glad to see it [moving](https://www.youtube.com/watch?v=Dyx4v1QFzhQ). Keep chugging and jump on the call with us tomorrow or Friday if you can.

**Comment by gordonje** [comment]
Looking good @aboutaaron 

Interested to hear more about your thinking behind the data format toggle. So would this allow users to either download a .zip of csv files or a .sql with all the `CREATE TABLE...`, `INSERT...`, etc. statements to set up a database? Could be helpful feature, and if we want to add might want to think about non-postgres users. Maybe want a separate gh issue if we're pursuing this.

I want to take a stab at listing the elements we want on this page, in order (cc @palewire)
1. Usual header stuff: nav, breadcrumbs, title, description
2. A "Processed" section with:
    - button and curl snippet for downloading processed.zip (or .sql)
    - a list of processed files, alpha sorted by group (Flat or Relational)
    - Note: we have files filter on the current versions of the page, but sort feels like overkill with only two groups no?
3. A "Raw" section with:
    - button and curl snippet for downloading clean.zip (or .sql)
    - a list of raw files, alpha sorted by group (Campaign, Common, Lobbying or Inactive)
    - keep this file filter?
4. An "Errata" section with raw data error logs listed alphabetically
5. Usual footer stuff

Or we could have separate pages:
- `./downloads/` for downloading the processed version or individual processed files
- `./downloads/raw/` for downloading the cleaned version or individual cleaned files (also includes errata).

The second route, I think, is where we ultimately want to end up as we publish more processed files and that data set becomes more comprehensive. But maybe too early for that?

**Comment by aboutaaron** [comment]
![desktop](https://user-images.githubusercontent.com/856628/30888114-cf74186c-a2ec-11e7-8224-511c1efe64dd.png)

Alright y'all, here's a rough conceptual draft of where I think we can. I like Honest Charlie's approach, but I'm always a fan of the "SHOW ME WHAT'S IMPORTANT" approach to design and storytelling.

In that regard, I re-did the top to emphasize the processed files. Folks can do a bulk download or fetch from our API via curl. So, that mostly mimics what we had originally.

The big addition is the idea of an "explore by topic section." On our beta site, we currently have all the flat/relation tables listed out, but what if I don't even know where to start? I think it'd be helpful to have pages dedicated to topics like candidates, ballot measures, elections, etc. From there, users would land on a page with all the relevant tables around the topic they're most interested in (and can choose whether to go with flat or relational.) I'm not sure how feasible this is given time/effort, but I think this is smart way to get folks using our stuff right away.

The bottom half of the page, will mimic the current version of our site for raw data. I think it's important to add a note that is effectively the _advanced_ section of the site and you should only download these raw files if you're interested in working with the source data directly. Basically we should discourage use of this section as much as possible.

I'll work on mocking up what a topic page could look like either later tonight or Thursday.

My hope with this design is to get users with our data as quickly as possible with having to think about format or database design. So, if all they wanna know is what Gavin Newsom is doing, we can just point them to the candidate topic page where they'll get most of what they need. This could also be a good place to include recipes or best ways to walk across different parts of the dataset.

Happy to hear from y'all. I'll try to be on the call tomorrow, but otherwise, Slack and email will always work. Thank you for your patience and sorry for lagging!

**Comment by palewire** [comment]
We can talk about it in the morning but my main concern here is that raw files remain pretty prominent and might be mistaken for the main dish.

**Comment by aboutaaron** [comment]
We could totally move the raw files to a separate page and just have it as a link at the end of this page.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by aboutaaron** [comment]
![desktop](https://user-images.githubusercontent.com/856628/31089404-e5ca8be4-a771-11e7-9040-829a4fe4cb0b.png)

Okay, here's the swing I took this weekend at redesign the page around our processed data files.

Per our convo last week, the page is broken up into four sections: simplified/flat tables (getting started), relational tables (advanced), raw data and errata. I don't think we need to link to the individual tables for Advanced/Raw since we should just send people to the doc pages for those.

My goal with the design was to get people using our stuff right away. Based on our chat, I killed the `curl` call for the "Getting started section since 1. there are only three tables at the moment and 2. that seems like overkill for a "getting started section. I know we also plan on adding future tables so I also added a *coming soon* style for the tables. I opted for a two-by-two layout since this section could expand in the future. We can stack 'em for mobile.

Another thing I want us to work on is the language for the page. We should try to make it very clear why you would want to use the flat tables over the relational ones. Even though I use SQL, the flat tables would be more appealing for building a quick graphic. So, I think we just gotta hammer these points in the copy (provided people read it.)

The page is pretty type heavy, which I actually don't mind for a data download page, but it could be smart to work in some iconography or other design elements to give the page some punch. But, I think this is a solid first step in how the page layout could work.

Ping me via Slack or here with any feedback. I'll be online late tonight so I can chat via Slack if y'all are around. I should also have a bit of time tomorrow provided the Vegas coverage dies down. I'll be online intermittently the rest of the week due to ONA but will try to respond where I can.

Thanks!

**Comment by gordonje** [comment]
Looking good @aboutaaron. Here are some thoughts/questions:

- I like the compressed layout for the "Available data" section. At most, we'll probably end up with 7-8 tables listed in the section, so this should work even as we add new flat files. I also like how you are 
displaying the tables that are "coming soon".
- Do we want users to be able to download individual flat files from this page? We'll need a clearer signal if those flat table names are supposed to be download links.
- The zip that's behind that download button at the top currently includes the flat and relation files. Is that confusing? Would it be better if it were just the flat files? Maybe we need a `processed-flat-files.zip` and a `processed-relational-files.zip` and the latter gets displayed in the "Advanced usage" section.
- Agree about not needing the list of raw data tables. I still think this section needs a clear link to those docs for the individual raw data files, maybe after the `curl` snippet.

**Comment by palewire** [comment]
@aboutaaron. After a little bootstrap hackery, I got that gray box to run the fill width of the page, just like the red bar. This the effect you were aiming for?

![screenshot from 2017-10-24 18-42-41](https://user-images.githubusercontent.com/9993/31976249-3605c620-b8eb-11e7-88a3-3b1a41dfbe15.png)

**Comment by aboutaaron** [comment]
@palewire Yes! Just planned to comment on this. This looks a lot cleaner and has the intended effect I was going for

**Comment by palewire** [comment]
Anything else you see? I'm in there hacking now on the development branch.

**Comment by aboutaaron** [comment]
@palewire I'll pull the latest done now. I'm also on Slack if you wanna chat there

**Comment by palewire** [comment]
![](https://media.giphy.com/media/l1BgS9aNtdCdjgkaQ/giphy.gif)
